#!/usr/bin/env python3
"""Offline shader coverage check of a shader package (.mesp / .mesp.idx) before a release.

Answers "which shaders that the game is known to use are NOT in this package, and where do they come from".

usage:
  tools/check_shader_coverage.py PACKAGE [--reference PKG ...] [--containers DIR] [--containers-json JSON]
                                 [--logs PATH ...] [--prewarm LIST.bin ...] [--json OUT.json] [-v]

PACKAGE / PKG   a masseffect_shaders.mesp or its .mesp.idx (the index is read when it exists: fast, no SPIR-V).
                Also accepted: a folder of *.bin containers (shaders/runtime_containers layout).
--reference     other packages (older console packages, the other edition, v27 lineage, ...). Every TABLE-LESS
                shader (Direct3D / Scaleform runtime shader: no CTAB or a CTAB with 0 constants) in a reference that
                is missing from PACKAGE and from --containers is reported: those are generated by default.xex at run
                time, so no disc scan can ever find them again; they only survive through shaders/runtime_containers.
--containers    shaders/runtime_containers (default: <repo>/shaders/runtime_containers when it exists).
--containers-json  installer/wasm/runtime_containers.json (what the public web installer bundles). Default: the repo's.
--logs          console logs or folders of logs (searched recursively for *.log / *.txt). Hashes are collected
                from 'unresolved draw shader pairs', 'unidentified pixel|vertex shader', 'missing shader draw' and
                'missing shader microcode' lines; complete microcode dumps are reassembled.
--prewarm       pipeline prewarm lists (NFPL, app/prewarm/*.bin): their records name shaders by container
                fingerprint.

Identities (they must match the runtime exactly):
  * microcode hash ("host hash", the PS=/VS= values of the logs) = XXH3-64 over the microcode words in host order
    (me_native_system.cpp CodeHash, masseffect_native_shaders.cpp Read: e.fingerprint for pixel shaders);
    the microcode is at virtual_size + shader_header.offset, shader_header.size bytes (2008 layout 0x102A11xx).
  * container fingerprint (prewarm lists, the .idx) = XXH3-64 of the whole original container.
  Vertex shaders arrive patched by Direct3D (fetch swizzles), so a VS hash of a log only matches a package VS when
  the shader was not patched; VS from logs are reported separately and are only proven missing with a microcode dump.

Exit code: 0 nothing missing, 1 something missing (containers the runtime ignores are listed as IGNORED, not fatal).
Needs the Python package 'xxhash' (python3 -m pip install xxhash).
"""
import argparse
import base64
import json
import os
import re
import struct
import sys

try:
    import xxhash
except ImportError:  # pragma: no cover
    sys.exit("error: the Python package 'xxhash' is required (python3 -m pip install xxhash)")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NFPL = 0x4C50464E
PREWARM_HEADER = 16
PREWARM_FP_OFFSET = 104  # sizeof(PipelineKey): u64 vs_fingerprint, u64 ps_fingerprint follow


def be32(b, o):
    return struct.unpack_from(">I", b, o)[0]


def xxh3(b):
    return xxhash.xxh3_64_intdigest(b)


FETCH_KEEPS = (0x0007FFFF, 0x80000FFF, 0x80000000)  # masseffect_native_shaders.cpp kFetchKeeps


def fetches_of_vertices(w):
    """masseffect_native_shaders.cpp FetchesOfVertices: (instruction, destination register) of every vertex fetch."""
    out = []
    end = len(w) // 3
    par = 0
    while par < end and par * 3 + 2 < len(w):
        cf = (w[par * 3] | ((w[par * 3 + 1] & 0xFFFF) << 32), (w[par * 3 + 1] >> 16) | (w[par * 3 + 2] << 16))
        for c in cf:
            op = (c >> 44) & 0xF
            if not (1 <= op <= 6 or op in (13, 14)):
                continue
            address, count, seq = c & 0xFFF, (c >> 12) & 0x7, (c >> 16) & 0xFFF
            if address:
                end = min(end, address)
            for i in range(count):
                index = address + i
                if not (seq >> (i * 2)) & 1 or index * 3 + 2 >= len(w):
                    continue
                if w[index * 3] & 0x1F:
                    continue
                out.append((index, (w[index * 3] >> 12) & 0x3F))
        par += 1
    return out


def mask_fetches(words, instructions):
    w = list(words)
    for ins in instructions:
        for j in range(3):
            if ins * 3 + j < len(w):
                w[ins * 3 + j] &= FETCH_KEEPS[j]
    return w


class Entry:
    __slots__ = ("number", "fingerprint", "vertex", "words", "code_hash", "table_less", "problem", "microcode",
                 "elements", "masked")

    def __init__(self, number, original):
        self.number = number
        self.fingerprint = xxh3(original)
        self.vertex = bool(be32(original, 0) & 1) if len(original) >= 4 else False
        self.words = 0
        self.code_hash = None
        self.table_less = False
        self.problem = None
        self.microcode = None
        self.elements = []   # VS: fetch instructions the runtime masks (identity = masked microcode)
        self.masked = None
        self._read(original)

    def _read(self, o):
        """The checks of masseffect_native_shaders.cpp Read() that make the runtime ignore a container."""
        n = len(o)
        if n < 28:
            self.problem = "container too short"
            return
        sig = be32(o, 0)
        if (sig & 0xFFFFFF00) != 0x102A1100:
            self.problem = "not a 2008 (0x102A11xx) container"
            return
        virtual = be32(o, 4)
        table = be32(o, 16)
        header = be32(o, 24)
        self.table_less = (not table) or (table + 20 <= n and be32(o, table + 16) == 0)
        if header + 8 > n:
            self.problem = "shader header outside the container"
            return
        offset, size = be32(o, header), be32(o, header + 4)
        start = virtual + offset
        if not size or size % 4 or start + size > n:
            self.problem = "microcode outside the container"
            return
        if header >= virtual or header + (40 if self.vertex else 32) > virtual:
            self.problem = "shader header outside the virtual part"
            return
        words = struct.unpack_from(">%dI" % (size // 4), o, start)
        self.words = len(words)
        self.microcode = words
        self.code_hash = xxh3(struct.pack("<%dI" % len(words), *words))
        if self.vertex:
            previous, count = be32(o, header + 24), be32(o, header + 28)
            begin = header + 36 + previous * 4
            if count > 64 or previous > 1024 or begin + count * 4 > virtual:
                self.problem = "vertex elements outside the virtual part"
                return
            if self.table_less:
                self.elements = [i for i, _ in fetches_of_vertices(words)]
            else:
                self.elements = [be32(o, begin + 4 * i) & 0xFFF for i in range(count)]
            self.masked = tuple(mask_fetches(words, self.elements))


class Package:
    def __init__(self, path):
        self.path = path
        self.entries = []
        if os.path.isdir(path):
            for name in sorted(os.listdir(path)):
                if name.endswith(".bin"):
                    with open(os.path.join(path, name), "rb") as f:
                        e = Entry(name, f.read())
                    self.entries.append(e)
        else:
            idx = path if path.endswith(".idx") else path + ".idx"
            if os.path.exists(idx):
                self._load_idx(idx)
            else:
                self._load_mesp(path)
        self.by_code = {}
        self.by_fp = {}
        self.vs_by_words = {}
        for e in self.entries:
            self.by_fp.setdefault(e.fingerprint, e)
            if e.code_hash is not None:
                self.by_code.setdefault((e.vertex, e.code_hash), []).append(e)
                if e.vertex and e.masked is not None:
                    self.vs_by_words.setdefault(e.words, []).append(e)

    def _load_idx(self, idx):
        data = open(idx, "rb").read()
        if data[:8] != b"MESSIDX\0":
            raise SystemExit(f"{idx}: not a shader package index")
        count = struct.unpack_from("<I", data, 12)[0]
        package_size = struct.unpack_from("<Q", data, 16)[0]
        mesp = idx[:-4]
        if os.path.exists(mesp) and os.path.getsize(mesp) != package_size:
            print(f"warning: {idx} belongs to a package of {package_size} bytes, {mesp} has "
                  f"{os.path.getsize(mesp)}: the runtime will not use this index", file=sys.stderr)
        pos = 56 + count * 40
        for i in range(count):
            original = struct.unpack_from("<I", data, 56 + i * 40)[0]
            stored = struct.unpack_from("<Q", data, 56 + i * 40 + 8)[0]
            e = Entry(i, data[pos:pos + original])
            if e.fingerprint != stored:
                e.problem = "container fingerprint differs from the index"
            self.entries.append(e)
            pos += original

    def _load_mesp(self, path):
        with open(path, "rb") as f:
            head = f.read(24)
            if head[:8] not in (b"MESSPV\0\0", b"NFSSPV\0\0"):  # NFSSPV: the older (v27) lineage, same layout
                raise SystemExit(f"{path}: not a shader package")
            count = struct.unpack_from("<I", head, 12)[0]
            for i in range(count):
                original, words = struct.unpack_from("<II", f.read(16), 0)
                e = Entry(i, f.read(original))
                f.seek(words * 4, os.SEEK_CUR)
                self.entries.append(e)

    def has_code(self, vertex, code_hash):
        return (vertex, code_hash) in self.by_code

    def identify_vs(self, words):
        """First stage of ShadersNative::Identify for a (possibly patched) VS microcode: mask the fetches of each
        same-length candidate and compare. Returns the entry or None (the runtime's second, permissive stage is
        not modelled, so None means 'not proven present')."""
        for e in self.vs_by_words.get(len(words), []):
            if tuple(mask_fetches(words, e.elements)) == e.masked:
                return e
        return None


def load_containers_json(path):
    out = {}
    for name, b64 in json.load(open(path)).items():
        out[name] = Entry(name, base64.b64decode(b64))
    return out


# ---------------------------------------------------------------------------------------------------------------
# Logs

RE_PAIR = re.compile(r"(\d+)x\(VS=([0-9A-F]{16}),PS=([0-9A-F]{16})\)")
RE_UNIDENT = re.compile(r"unidentified (pixel|vertex) shader: (\d+) words, fingerprint ([0-9A-F]{16})")
RE_MISSING_DRAW = re.compile(r"missing shader draw: VS ([0-9A-F]{16}) (found|MISSING).*?PS ([0-9A-F]{16}) (found|MISSING)")
RE_MICRO = re.compile(r"missing shader microcode (VS|PS) ([0-9A-F]{16}) (\d+) words \[(\d+)\]:((?: [0-9A-F]{8})+)")


class Seen:
    def __init__(self, vertex, h):
        self.vertex = vertex
        self.hash = h
        self.words = None
        self.logs = set()
        self.draws = 0          # max cumulative 'unresolved draw shader pairs' count of one log
        self.microcode = {}     # index -> word (from 'missing shader microcode')


def scan_logs(paths):
    seen = {}

    def get(vertex, h):
        key = (vertex, int(h, 16))
        if key not in seen:
            seen[key] = Seen(vertex, key[1])
        return seen[key]

    files = []
    for p in paths:
        if os.path.isdir(p):
            for root, _, names in os.walk(p):
                files += [os.path.join(root, n) for n in names if n.endswith((".log", ".txt"))]
        elif os.path.exists(p):
            files.append(p)
    for path in sorted(files):
        try:
            text = open(path, "r", errors="replace").read()
        except OSError:
            continue
        if "shader" not in text:
            continue
        per_log = {}
        for line in text.splitlines():
            if "unresolved draw shader pairs" in line:
                for count, vs, ps in RE_PAIR.findall(line):
                    # VS=0 means the VS was identified and the PS is missing, and the reverse.
                    if ps != "0" * 16 and vs == "0" * 16:
                        k = (False, ps)
                    elif vs != "0" * 16 and ps == "0" * 16:
                        k = (True, vs)
                    else:
                        for kk in ((True, vs), (False, ps)):
                            if kk[1] != "0" * 16:
                                per_log[kk] = max(per_log.get(kk, 0), int(count))
                        continue
                    per_log[k] = max(per_log.get(k, 0), int(count))
                continue
            m = RE_UNIDENT.search(line)
            if m:
                s = get(m.group(1) == "vertex", m.group(3))
                s.words = int(m.group(2))
                s.logs.add(path)
                continue
            m = RE_MISSING_DRAW.search(line)
            if m:
                if m.group(2) == "MISSING":
                    get(True, m.group(1)).logs.add(path)
                if m.group(4) == "MISSING":
                    get(False, m.group(3)).logs.add(path)
                continue
            m = RE_MICRO.search(line)
            if m:
                s = get(m.group(1) == "VS", m.group(2))
                s.words = int(m.group(3))
                first = int(m.group(4))
                for i, w in enumerate(m.group(5).split()):
                    s.microcode[first + i] = int(w, 16)
                s.logs.add(path)
        for (vertex, h), count in per_log.items():
            s = get(vertex, h)
            s.logs.add(path)
            s.draws = max(s.draws, count)
    for s in seen.values():
        if s.words and len(s.microcode) == s.words:
            words = [s.microcode[i] for i in range(s.words)]
            if xxh3(struct.pack("<%dI" % s.words, *words)) != s.hash:
                s.microcode = {}  # incomplete or mixed dump
        else:
            s.microcode = {}
    return seen


def read_prewarm(path):
    data = open(path, "rb").read()
    magic, version, size, count = struct.unpack_from("<IIII", data, 0)
    if magic != NFPL or len(data) != PREWARM_HEADER + size * count:
        raise SystemExit(f"{path}: not a prewarm list")
    fps = set()
    for i in range(count):
        r = PREWARM_HEADER + i * size
        ps_number = struct.unpack_from("<I", data, r + 4)[0]
        vs_fp, ps_fp = struct.unpack_from("<QQ", data, r + PREWARM_FP_OFFSET)
        if vs_fp:
            fps.add((True, vs_fp))
        if ps_number and ps_fp:
            fps.add((False, ps_fp))
    return fps


# ---------------------------------------------------------------------------------------------------------------

def stage(vertex):
    return "VS" if vertex else "PS"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("package")
    ap.add_argument("--reference", action="append", default=[])
    ap.add_argument("--containers", default=os.path.join(REPO, "shaders", "runtime_containers"))
    ap.add_argument("--containers-json", default=os.path.join(REPO, "installer", "wasm", "runtime_containers.json"))
    ap.add_argument("--logs", action="append", default=[])
    ap.add_argument("--prewarm", action="append", default=[])
    ap.add_argument("--json", help="write the findings as JSON")
    ap.add_argument("-v", "--verbose", action="store_true")
    a = ap.parse_args()

    target = Package(a.package)
    containers = Package(a.containers) if a.containers and os.path.isdir(a.containers) else None
    bundled = load_containers_json(a.containers_json) if a.containers_json and os.path.exists(a.containers_json) else {}
    refs = [Package(p) for p in a.reference]
    findings = {"package": a.package, "entries": len(target.entries), "ignored_by_runtime": [],
                "runtime_containers_missing": [], "folder_vs_json": [], "reference_table_less_missing": [],
                "reference_other_missing": 0, "logged_missing": [], "prewarm_missing": []}
    bad = 0

    def where(vertex, h):
        out = []
        if containers and containers.has_code(vertex, h):
            out.append("runtime_containers/" + ",".join(str(e.number) for e in containers.by_code[(vertex, h)]))
        if any(e.code_hash == h and e.vertex == vertex for e in bundled.values()):
            out.append("installer-json")
        for r in refs:
            for e in r.by_code.get((vertex, h), [])[:1]:
                out.append(f"{os.path.basename(os.path.dirname(r.path)) or r.path}#{e.number}"
                           f"({'table-less' if e.table_less else 'CTAB'})")
        return out

    print(f"package {a.package}: {len(target.entries)} containers, "
          f"{sum(1 for e in target.entries if not e.problem)} usable by the runtime, "
          f"{len(target.by_code)} distinct (stage, microcode)")

    # 1. Containers the runtime ignores (masseffect_native_shaders.cpp Read()).
    for e in target.entries:
        if e.problem:  # harmless (the runtime skips it with a warning), not fatal: scanner false positives
            findings["ignored_by_runtime"].append({"number": e.number, "fingerprint": f"{e.fingerprint:016X}",
                                                   "reason": e.problem})
            print(f"IGNORED  container {e.number} ({e.fingerprint:016X}): {e.problem}")

    # 2. shaders/runtime_containers and the installer's JSON: every one must be in the package, and both must agree.
    if containers:
        for e in containers.entries:
            if e.problem:
                bad += 1
                print(f"BROKEN   runtime container {e.number}: {e.problem}")
            elif not target.has_code(e.vertex, e.code_hash):
                bad += 1
                findings["runtime_containers_missing"].append(e.number)
                print(f"MISSING  runtime container {e.number} ({stage(e.vertex)} {e.code_hash:016X}, {e.words} words)")
        names = {e.number for e in containers.entries}
        for n in sorted(names ^ set(bundled)):
            bad += 1
            side = "folder only" if n in names else "installer JSON only"
            findings["folder_vs_json"].append({"name": n, "side": side})
            print(f"DIFFERS  {n}: {side} (regenerate installer/wasm/runtime_containers.json)")
        for n in sorted(names & set(bundled)):
            c = next(e for e in containers.entries if e.number == n)
            if c.fingerprint != bundled[n].fingerprint:
                bad += 1
                findings["folder_vs_json"].append({"name": n, "side": "content differs"})
                print(f"DIFFERS  {n}: folder and installer JSON contents differ")

    # 3. Reference packages: table-less shaders missing from the package and from runtime_containers.
    for r in refs:
        missing_tl, other = [], 0
        for (vertex, h), es in r.by_code.items():
            if target.has_code(vertex, h):
                continue
            e = es[0]
            if e.table_less:
                in_rc = containers.has_code(vertex, h) if containers else False
                missing_tl.append((e, in_rc))
            else:
                other += 1
        findings["reference_other_missing"] += other
        print(f"reference {r.path}: {len(r.entries)} containers; missing from the package: {len(missing_tl)} "
              f"table-less (runtime) shaders, {other} CTAB (disc package) shaders")
        for e, in_rc in sorted(missing_tl, key=lambda t: (t[0].vertex, t[0].words)):
            bad += 1
            findings["reference_table_less_missing"].append({
                "reference": r.path, "stage": stage(e.vertex), "hash": f"{e.code_hash:016X}", "words": e.words,
                "container": f"{e.fingerprint:016X}", "in_runtime_containers": in_rc})
            print(f"MISSING  table-less {stage(e.vertex)} {e.code_hash:016X} ({e.words} words, container "
                  f"{e.fingerprint:016X}, ref #{e.number}){' [in runtime_containers]' if in_rc else ''}")

    # 4. Hashes the console reported.
    if a.logs:
        seen = scan_logs(a.logs)
        rows = []
        for (vertex, h), s in seen.items():
            if target.has_code(vertex, h):
                continue
            if vertex and s.microcode and target.identify_vs([s.microcode[i] for i in range(s.words)]):
                continue  # a fetch-patched variant of a package VS
            rows.append(s)
        rows.sort(key=lambda s: (-s.draws, s.vertex, s.hash))
        print(f"logs: {len(seen)} distinct shader hashes reported, {len(rows)} not in the package "
              "(by unpatched microcode hash)")
        for s in rows:
            w = where(s.vertex, s.hash)
            kind = ("runtime" if any("table-less" in x or x.startswith(("runtime_containers", "installer"))
                                     for x in w) else "disc" if any("CTAB" in x for x in w) else "unknown")
            if s.vertex and not w:
                # Direct3D patches VS fetches, so a logged VS hash is not proof: the runtime's second (patched-fetch)
                # lookup may still find it. Reported, not fatal; a later log with the same package decides.
                kind = "VS (not proven missing: patched at run time)" + ("" if s.microcode else ", no microcode dump")
            else:
                bad += 1
            findings["logged_missing"].append({
                "stage": stage(s.vertex), "hash": f"{s.hash:016X}", "words": s.words, "max_draws": s.draws,
                "logs": len(s.logs), "kind": kind, "found_in": w, "microcode_in_log": bool(s.microcode),
                "example_log": sorted(s.logs)[-1] if s.logs else None})
            print(f"LOGGED   {stage(s.vertex)} {s.hash:016X} words={s.words} max_draws={s.draws} logs={len(s.logs)} "
                  f"kind={kind} found_in={','.join(w) or '-'}{' microcode-in-log' if s.microcode else ''}")
            if a.verbose:
                for p in sorted(s.logs)[-3:]:
                    print(f"           {p}")

    # 5. Prewarm lists (container fingerprints).
    for p in a.prewarm:
        fps = read_prewarm(p)
        miss = [(v, fp) for v, fp in fps if fp not in target.by_fp]
        print(f"prewarm {p}: {len(fps)} distinct shaders, {len(miss)} not in the package")
        for v, fp in sorted(miss):
            findings["prewarm_missing"].append({"list": p, "stage": stage(v), "container": f"{fp:016X}"})
            if a.verbose:
                print(f"PREWARM  {stage(v)} container {fp:016X} not in the package")
        # A list recorded against another package only loses pipelines (a cold-start hitch), not draws.

    if a.json:
        with open(a.json, "w") as f:
            json.dump(findings, f, indent=1)
    print("RESULT: " + ("problems found" if bad else "ok"))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
